### ISSUE TITLE
Estudo e implementação do MkDocs no GitHub Pages

### ISSUE THREAD

**Issue by Julio-eng** [fga-eps-mds/2022-1-PokeRanking#10]
## Descrição

Estudar sobre o MkDocs, um gerador de páginas estáticas para a documentação de projetos, que pode ser utilizado para criar o GitHub Pages do nosso projeto.

## Tarefas

- [x] Pesquisar e entender como o MkDocs funciona
- [x] Implementar uma página para testes
- [x] Implementar uma versão inicial no nosso repositório

## Critérios de Aceitação

- [x] Explicar para a equipe o que foi pesquisado.
- [x] Disponibilizar o link para acesso da versão inicial do GitHub Pages 

## Informação adicional

Documentação do MkDocs: https://www.mkdocs.org/getting-started/

**Comment by charles-serafim** [comment]
Links úteis:
- [Repositório MkDocs no GitHub](https://github.com/mkdocs/mkdocs)
- [MkDocs Wiki](https://github.com/mkdocs/mkdocs/wiki) - Contém temas, plugins e outros recursos.

**Comment by charles-serafim** [comment]
Vídeo bem didático explicando como usar alguns recursos do MkDocs: [Documentado projetos com MkDocs](https://youtu.be/GW6nAJ1NHUQ)

**Comment by charles-serafim** [comment]
Versão inicial implementada com sucesso!

Link: [PokéRanking](https://fga-eps-mds.github.io/2022-1-PokeRanking/)
