### ISSUE TITLE
Estudo de tecnologias back-end

### ISSUE THREAD

**Issue by artur-seppa** [fga-eps-mds/2022-1-PokeRanking#33]
## Descrição

Estudar as tecnologias escolhidas para o back-end.

## Tarefas

- [x] NodeJS
- [x] MongoDB

## Critérios de Aceitação

- [x] Ter um entendimento básico das tecnologias back-end que utilizaremos no projeto.

## Informação adicional

Fazer uso da plataforma [rocketseat](https://app.rocketseat.com.br/) como ferramenta de estudo.

**Comment by kazpmcd** [comment]
Página que explica a diferença entre node.js e express.js: https://blog.back4app.com/pt/diferencas-node-js-e-express-js/#:~:text=Express%20%C3%A9%20a%20estrutura%20da,HTTP%20em%20um%20determinado%20URL.

**Comment by JoaoSchmitz** [comment]
### Node.js: Iniciando da teoria à prática
https://youtu.be/DiXbJL3iWVs
### Como ler arquivo .csv com NodeJS
https://youtu.be/moQRSQR1ATw

**Comment by artur-seppa** [comment]
### Conectando Node.js com MongoDB
https://www.youtube.com/watch?v=4nO0BERnkc0
